Addressing problems raised in sphinx_issues #10104
sphinx-doc/sphinx-intl pull request #61
Opened 2022-04-23 06:31 UTC by hoangduytranuk

Added sort_output=False and sort_by_message_location=False so these flags can be controlled by users when dumping the po files manually and making use of the internal sort_output (sort the msgid alphabetically when writing to file) or sort_by_message_location (internally known as sort_by_file)

2022-04-24 07:49 UTC, shimizukawa requested changes
@hoangduytranuk please check my comment and update docstring (or code-comment).

2022-04-24 07:49 UTC, shimizukawa commented on sphinx_intl/catalog.py
> +        pofile.write_po(f, catalog, line_width, sort_output=sort_output, sort_by_file=sort_by_message_location)
Memo

https://babel.pocoo.org/en/latest/api/messages/pofile.html#babel.messages.pofile.write_po

* `sort_output` – whether to sort the messages in the output by msgid
* `sort_by_file` – whether to sort the messages in the output by their locations

defaults are False: `sort_output=False, sort_by_file=False`

2022-04-24 07:49 UTC, shimizukawa commented on sphinx_intl/catalog.py
> +def dump_po(filename, catalog, line_width=76, sort_output=False, sort_by_message_location=False):
Please add param lines on docstring for new 2 parameters.

These two arguments are not set to True within this tool and may be removed as unnecessary arguments. As a remedy, please describe the purpose for which they are arguments in the docstring or code comment.

2025-05-08 04:16 UTC, rffontenelle commented
@hoangduytranuk  Considering the merged #65, should this be closed or reworked?

2025-08-02 00:45 UTC, shimizukawa commented
This PR has not been updated for a long time, so I will close it once.
There are also file conflicts, please create another PR if you would like to update it.
Thanks.

2025-08-02 00:45 UTC, closed without merging